# image: http://docker.codethat.rocks:5000/discord-soundboard:0.0.10
# script:
#   - ./.drone/build.sh
# deploy:
#   bash:
#     script:
#       - ./drone/deploy.sh
# notify:
#   email:
#     recipients:
#       - email@example.com
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache

  docker:
    image: plugins/docker
    repo: registry.codethat.rocks:5000/discord-soundboard
    registry: registry.codethat.rocks:5000
    tags: latest
    debug: true
    storage_path: /drone/docker
    # Seems to be required to push to the registry on the same host
    custom_dns: [ 192.168.5.1 ]
    network_mode: host

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache

  rancher:
    image: peloton/drone-rancher
    url: http://rancher.codethat.rocks:8080
    access_key: superaccesskey
    secret_key: supersecretkey
    service: discordbot/discordbot
    docker_image: registry.codethat.rocks:5000/discord-soundboard
