# image: http://docker.codethat.rocks:5000/discord-soundboard:0.0.10
# script:
#   - ./.drone/build.sh
# deploy:
#   bash:
#     script:
#       - ./drone/deploy.sh
# notify:
#   email:
#     recipients:
#       - email@example.com
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache

  # Dev build
  docker-build:
    image: plugins/docker
    repo: registry.codethat.rocks:5000/discord-soundboard
    registry: registry.codethat.rocks:5000
    tags: dev-${CI_BUILD_NUMBER}
    debug: true
    storage_path: /drone/docker
    # Seems to be required to push to the registry on the same host
    custom_dns: [ 192.168.5.1 ]
    network_mode: host

  # On master, build the tagged version. Ideally replace this with an auto-semver
  get_tags:
    image: golang:1.10.0-alpine
    commands:
      - cat public/version.pug > .tags
    when:
      branch: master
  docker-build-release:
    image: plugins/docker
    repo: registry.codethat.rocks:5000/discord-soundboard
    registry: registry.codethat.rocks:5000
    default_tags: true
    debug: true
    storage_path: /drone/docker
    # Seems to be required to push to the registry on the same host
    custom_dns: [ 192.168.5.1 ]
    network_mode: host
    when:
      branch: master

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache

  rancher-dev:
    image: peloton/drone-rancher
    url: http://rancher.codethat.rocks:8080
    access_key: superaccesskey
    secret_key: supersecretkey
    service: dev-discord/discordbot
    docker_image: "registry.codethat.rocks:5000/discord-soundboard:dev-${CI_BUILD_NUMBER}"
    start_first: false
    confirm: true

  rancher-production:
    image: peloton/drone-rancher
    url: http://rancher.codethat.rocks:8080
    access_key: superaccesskey
    secret_key: supersecretkey
    service: discordbot/discordbot
    docker_image: registry.codethat.rocks:5000/discord-soundboard:0.0.11
    confirm: true
    when:
      branch: master