FROM node:18-alpine

# libasound2-dev for audio parsing
# sox for transcoding for speech to text
RUN apt-get update && apt-get install -y \
	  git \
	  ffmpeg \
	  libasound2-dev \
	  sox \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /node/stt

COPY package.json /node/

# node-gyp has to be built in alpine, but not kept for runtime
RUN apk add --no-cache --virtual .build-deps make gcc g++ python3 \
  && cd /node && npm install --production --silent \
  && apk del .build-deps
