FROM node:10-alpine

RUN apk add --no-cache jq git \
 && npm install --no-save \
      semantic-release \
      @semantic-release/exec \
      @semantic-release/changelog \
      @semantic-release/git
