FROM node:10.9-jessie

RUN echo "deb http://ftp.uk.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/backports.list \
 && apt-get update && apt-get install -y ffmpeg \
 && rm -rf /var/lib/apt/lists/*

COPY package.json /node/

RUN cd /node && npm install