FROM node:10-alpine

RUN apk add --no-cache jq git openssh-client \
 && npm install -g --no-save --no-optional \
      semantic-release \
      @semantic-release/exec \
      @semantic-release/changelog \
      @semantic-release/git
